### ISSUE TITLE
[紧急求助]最新版CityListSelect显示异常

### ISSUE THREAD

**Issue by Masksam** [crazyandcoder/citypicker#145]
```
04-13 10:49:17.119 18296-18296/com.eosine.driver W/System.err: java.io.IOException: BufferedInputStream is closed
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.io.BufferedInputStream.streamClosed(BufferedInputStream.java:125)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:231)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.io.BufferedReader.readChar(BufferedReader.java:263)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.io.BufferedReader.read(BufferedReader.java:253)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.util.Properties.load(Properties.java:289)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.util.Properties.load(Properties.java:248)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.ChineseToPinyinResource.initializeResource(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.ChineseToPinyinResource.<init>(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.ChineseToPinyinResource.<init>(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.ChineseToPinyinResource$ChineseToPinyinResourceHolder.<clinit>(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.ChineseToPinyinResource.getInstance(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.PinyinHelper.getUnformattedHanyuPinyinStringArray(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.PinyinHelper.getFormattedHanyuPinyinStringArray(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at net.sourceforge.pinyin4j.PinyinHelper.toHanyuPinyinStringArray(Unknown Source)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at com.lljjcoder.utils.PinYinUtils.getCharPinYin(PinYinUtils.java:46)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at com.lljjcoder.utils.PinYinUtils.getStringPinYin(PinYinUtils.java:75)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at com.lljjcoder.style.citylist.CityListSelectActivity.filledData(CityListSelectActivity.java:154)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at com.lljjcoder.style.citylist.CityListSelectActivity.setCityData(CityListSelectActivity.java:117)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at com.lljjcoder.style.citylist.CityListSelectActivity.onCreate(CityListSelectActivity.java:85)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.app.Activity.performCreate(Activity.java:6092)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:178)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.os.Looper.loop(Looper.java:194)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5637)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
04-13 10:49:17.120 18296-18296/com.eosine.driver W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Comment by crazyandcoder** [comment]
试试最新4.2.1版本
