### ISSUE TITLE
自定义数据源崩溃：No package ID ff found for ID 0xfffffba9.

### ISSUE THREAD

**Issue by xaEHu** [crazyandcoder/citypicker#205]
android.content.res.Resources$NotFoundException: Resource ID #0xfffffba9
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:239)
        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2317)
        at android.content.res.Resources.getLayout(Resources.java:1191)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at com.lljjcoder.style.citypickerview.widget.wheel.adapters.AbstractWheelTextAdapter.getView(AbstractWheelTextAdapter.java:283)
        at com.lljjcoder.style.citypickerview.widget.wheel.adapters.AbstractWheelTextAdapter.getItem(AbstractWheelTextAdapter.java:201)
        at com.lljjcoder.style.citypickerview.widget.wheel.WheelView.getItemView(WheelView.java:1049)
        at com.lljjcoder.style.citypickerview.widget.wheel.WheelView.addViewItem(WheelView.java:1002)
        at com.lljjcoder.style.citypickerview.widget.wheel.WheelView.buildViewForMeasuring(WheelView.java:988)
        at com.lljjcoder.style.citypickerview.widget.wheel.WheelView.onMeasure(WheelView.java:639)

代码是这样的：
`customCityPicker = new CustomCityPicker(this);
        List<CustomCityData> list = getCityChildList(bean);
        CustomConfig cityConfig = new CustomConfig.Builder()
                .title("请选择省市区")
                .visibleItemsCount(5)
                .setCityData(list)//设置数据源
                .provinceCyclic(false)
                .cityCyclic(false)
                .districtCyclic(false)
                .build();

        customCityPicker.setCustomConfig(cityConfig);
        customCityPicker.setOnCustomCityPickerItemClickListener(new OnCustomCityPickerItemClickListener() {
            @SuppressLint("SetTextI18n")
            @Override
            public void onSelected(CustomCityData province, CustomCityData city, CustomCityData district) {
                if (province != null && city != null && district != null) {
                    tvCity.setText(province.getName() + city.getName() + district.getName());
                    recordsBean.setProvinceCode(province.getId());
                    recordsBean.setProvinceName(province.getName());
                    recordsBean.setCityCode(city.getId());
                    recordsBean.setCityName(city.getName());
                    recordsBean.setDistrictCode(district.getId());
                    recordsBean.setDistrictName(district.getName());
                    isCitySetted = true;
                } else {
                    showToast("结果出错！");
                    isCitySetted = false;
                }
            }
        });

        if (isShow) {
            hideLoading();
            customCityPicker.showCityPicker();
        }`

**Comment by xaEHu** [comment]
5.2.4版本报的异常，换成5.2.2不会报这个异常

**Comment by hjywyj** [comment]
解决了吗

**Comment by crazyandcoder** [comment]
@xaEHu @hjywyj 对比一下demo看看，有什么区别 [demo URL](https://github.com/crazyandcoder/citypicker/blob/master/app/src/main/java/com/ihidea/as/citypicker/activity/CityPickerCustomeDataActivity.java)

**Comment by hjywyj** [comment]
好吧，还得加自定义布局文件，加了2行代码就好了，懒得加layout了
config.setCustomItemLayout(android.R.layout.simple_list_item_1)
                    .setCustomItemTextViewId(android.R.id.text1)

**Comment by xaEHu** [comment]
> 解决了吗

我用回5.2.2版本……

**Comment by crazyandcoder** [comment]
请添加自定义布局文件
