### ISSUE TITLE
数组越界了，我想从一个activity跳转到一个dialogactivity然后显示在下方

### ISSUE THREAD

**Issue by NovaMagician** [crazyandcoder/citypicker#47]
FATAL EXCEPTION: main
                                                                 Process: com.ouju.mlmcms, PID: 30681
                                                                 java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                     at com.lljjcoder.city_20170724.CityPickerView.updateAreas(CityPickerView.java:819)
                                                                     at com.lljjcoder.city_20170724.CityPickerView.updateCities(CityPickerView.java:778)
                                                                     at com.lljjcoder.city_20170724.CityPickerView.onChanged(CityPickerView.java:852)
                                                                     at com.lljjcoder.citypickerview.widget.wheel.WheelView.notifyChangingListeners(WheelView.java:296)
                                                                     at com.lljjcoder.citypickerview.widget.wheel.WheelView.setCurrentItem(WheelView.java:412)
                                                                     at com.lljjcoder.citypickerview.widget.wheel.WheelView.doScroll(WheelView.java:820)
                                                                     at com.lljjcoder.citypickerview.widget.wheel.WheelView.access$100(WheelView.java:48)
                                                                     at com.lljjcoder.citypickerview.widget.wheel.WheelView$1.onScroll(WheelView.java:169)
                                                                     at com.lljjcoder.citypickerview.widget.wheel.WheelScroller$2.handleMessage(WheelScroller.java:206)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:150)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by crazyandcoder** [comment]
@NovaMagician  已修复
