### ISSUE TITLE
vivo x9plus    7.11     java.lang.IllegalArgumentException: Unknown color 

### ISSUE THREAD

**Issue by jasonsyf** [crazyandcoder/citypicker#70]
java.lang.IllegalArgumentException: Unknown color
                                                                               at android.graphics.Color.parseColor(Color.java:163)
                                                                               at com.lljjcoder.citywheel.CityPickerView.updateCities(CityPickerView.java:257)
                                                                               at com.lljjcoder.citywheel.CityPickerView.onChanged(CityPickerView.java:370)
                                                                               at com.lljjcoder.citypickerview.widget.wheel.WheelView.notifyChangingListeners(WheelView.java:296)
                                                                               at com.lljjcoder.citypickerview.widget.wheel.WheelView.setCurrentItem(WheelView.java:412)
                                                                               at com.lljjcoder.citypickerview.widget.wheel.WheelView.setCurrentItem(WheelView.java:425)
                                                                               at com.lljjcoder.citywheel.CityPickerView.setUpData(CityPickerView.java:201)
                                                                               at com.lljjcoder.citywheel.CityPickerView.show(CityPickerView.java:347)
                                                                               at com.sinotech.oms.main.hsh.homepage.placeorder.CustomOrderActivity.selectAddress(CustomOrderActivity.java:160)
                                                                               at com.sinotech.oms.main.hsh.homepage.placeorder.CustomOrderActivity.onViewClicked(CustomOrderActivity.java:116)
                                                                               at com.sinotech.oms.main.hsh.homepage.placeorder.CustomOrderActivity_ViewBinding$2.doClick(CustomOrderActivity_ViewBinding.java:53)
                                                                               at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                               at android.view.View.performClick(View.java:5642)
                                                                               at android.view.View$PerformClick.run(View.java:22491)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6295)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)

**Comment by wppwzk** [comment]
以我的经验，遇到 Unknown color一般是.9图片的问题，你检查下资源文件

**Comment by crazyandcoder** [comment]
@jasonsyf  颜色值需要加“#”的十六进制的颜色值，检查一下是否设置正确
